### ISSUE TITLE
post to getlektor.com?

### ISSUE THREAD

**Issue by nixjdm** [SoftInstigate/lektor-gulp#1]
Hey @mkjsix and SoftInstigate folk! I'm Lektor's maintainer, and I found your plugin. I want to encourage you to open a pull request to https://github.com/lektor/lektor-website to add it to the list of available plugins. You can read about how to do that here: https://www.getlektor.com/docs/plugins/publishing/

I hope you do!

Thanks!

**Comment by mkjsix** [comment]
Hi @nixjdm 
I eventually found the time to improve a bit the project's docs and open the PR, please let me know if it's ok. 
Thank you

**Comment by nixjdm** [comment]
It looks good to me, and it's pulled! Thanks!
