### ISSUE TITLE
lektor plugins add lektor-gulp old version

### ISSUE THREAD

**Issue by roberto-arista** [SoftInstigate/lektor-gulp#3]
Hi! 
I just tried to install lektor-gulp through lektor cli and version 0.1.0 was installed. It does not work, instead manually fixing the .lektorproject file with the correct version number fixed my issue. You might want to take action on this...

Cheers

**Comment by mkjsix** [comment]
Hi @roberto-arista 
Could you please provide me with the exact lektor cli command which installed the wrong version number? I usually just add it by editing the .lektorproject by hand.

The PyPy version is 0.3.2: https://pypi.org/project/lektor-gulp/
The Lektor docs point to 0.3.2: https://www.getlektor.com/plugins/lektor-gulp/

[Lektor docs](https://www.getlektor.com/docs/plugins/) say:

## Installing Published Plugins
Lektor can find and install plugins that have been published to PyPI for you. For completely automated plugin management just open your project file in a text editor and edit or extend the [packages] section. Just add a line for each plugin in the form name = version:

```
[packages]
lektor-gulp = 0.3.2
```

So I have no clue on what I could do on my side.

**Comment by roberto-arista** [comment]
I used
`lektor plugins add lektor-gulp`

**Comment by mkjsix** [comment]
I have Lektor version 3.1.3.

I created a "test" project with `lektor quickstart`

Then I ran the following commands:

```bash
$ lektor plugins add lektor-gulp
Package lektor-gulp (0.3.2) was added to the project

$ cat test.lektorproject 
[project]
name = test

[packages]
lektor-gulp = 0.3.2
```

So in my case lektor is installing the right plugin version (0.3.2 is the latest), I don't really know why is not working in your case, maybe you have a different installed version. I could only suggest you to check with the [Lektor project itself](https://github.com/lektor/lektor/issues) mentioning this issue.

**Comment by mkjsix** [comment]
BTW, maybe the problem is with you version of pip, which could be old. Try updating pip and see if it fixes the issue.

See [this thread](https://stackoverflow.com/a/22013957/615095) for more.

**Comment by roberto-arista** [comment]
That's weird, I just made a new installation in a test folder and it works fine. 
I didn't upgrade pip, it wasn't necessary.

Good to know that works properly and it was an issue on my end.
Sorry for the trouble, and thanks for the support!
